name: notado
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_speed_dial: ^1.2.5
  curved_navigation_bar: ^0.3.3
  provider: ^4.3.1
  image_picker: ^0.6.7+4
  font_awesome_flutter: ^8.8.1
  shared_preferences: ^0.5.1
  intl: ^0.16.1
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  async_loader: ^0.1.1
  firebase_storage: ^3.1.6
  http: ^0.12.2
  cloud_firestore: ^0.13.4+2
  flutter_spinkit: "^4.1.2"
  flutter_bloc: ^6.0.1
  rxdart:
  equatable: ^1.2.0
  bloc: ^6.0.0
  meta: ^1.1.8
  uuid: ^2.1.0
  email_validator: ^1.0.5
  convex_bottom_bar: ^2.4.1
  flutter_material_color_picker: ^1.0.5
  flutter_staggered_grid_view: ^0.3.2
  avatar_glow: ^1.2.0
  zefyr: ^0.11.0
  quill_delta: ^1.0.2
  data_connection_checker: ^0.3.4
  url_launcher: ^5.5.1
  toast: ^0.1.5
  flutter_svg: ^0.19.0
  firebase_analytics: any
  # pull_to_refresh: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
